# Generated by Django 3.1 on 2022-02-09 16:56

import core.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210608_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('minimum_age_allowed', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, db_index=False)),
                ('address', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('state', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('country', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('iso_code', models.CharField(max_length=2, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile')),
                ('timezone', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('ordering_feature_active', models.BooleanField(default=False)),
                ('has_orders', models.BooleanField(default=False)),
                ('total_amount_earned', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('total_amount_received', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '[Business Profile] ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_open', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('mo_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('mo_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '[Business Profile] Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_open', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('mo_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('mo_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '[User Profile] Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('d_o_b', models.DateField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=10)),
                ('timezone', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('time', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('total_seconds', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('country', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('iso_code', models.CharField(max_length=2, null=True)),
                ('card_information', models.CharField(default='[]', max_length=1000000, null=True)),
            ],
            options={
                'verbose_name': '[User Profile]',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='business_signup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='items',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='business',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='special_line',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='present_line',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='special_line',
        ),
        migrations.RemoveField(
            model_name='user_signup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business_line',
        ),
        migrations.DeleteModel(
            name='Business_signup',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Special_line',
        ),
        migrations.DeleteModel(
            name='User_signup',
        ),
    ]
