# Generated by Django 3.1 on 2022-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='d_o_b',
            field=models.DateField(blank=True),
        ),
    ]
