# Generated by Django 3.1 on 2022-02-18 10:11

import core.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', core.common.fields.DefaultTextField(blank=True, null=True)),
                ('items', models.CharField(max_length=10485760)),
                ('total', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('status', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('pin', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('has_been_actived', models.BooleanField(default=False)),
                ('order_status', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('ready_time', core.common.fields.DefaultDateTimeField(blank=True, null=True)),
                ('user_has_seen_notification', models.BooleanField(default=False)),
                ('fees', models.FloatField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='account.businessprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='account.userprofile')),
            ],
            options={
                'verbose_name': '[Order]',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('price', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('units_available', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='account.businessprofile')),
            ],
            options={
                'verbose_name': '[ Item ]',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('instruction', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('information', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('slug', models.SlugField(db_index=False, max_length=80)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='queue', to='account.businessprofile')),
            ],
            options={
                'verbose_name': '[ Business Queue ]',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('bank', core.common.fields.DefaultTextField(blank=True, null=True)),
                ('account_name', core.common.fields.DefaultTextField(blank=True, null=True)),
                ('recipient_info', core.common.fields.DefaultTextField(blank=True, null=True)),
                ('email_confirmation', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank', to='account.businessprofile')),
            ],
            options={
                'verbose_name': '[Business Profile] Bank',
                'ordering': ['-created_at'],
            },
        ),
    ]
