# Generated by Django 3.1 on 2022-03-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220308_1323'),
        ('business', '0007_auto_20220308_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank', to='account.businessprofile'),
        ),
    ]
