# Generated by Django 3.1 on 2022-03-08 13:36

import core.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20220308_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=core.common.fields.DefaultCharField(blank=True, max_length=255, null=True),
        ),
    ]
