# Generated by Django 3.1 on 2022-03-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20220303_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='business',
            new_name='owner',
        ),
    ]
