# Generated by Django 3.1 on 2022-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220303_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessqueue',
            old_name='business',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='businessqueue',
            name='slug',
        ),
        migrations.AlterField(
            model_name='businessqueue',
            name='information',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='businessqueue',
            name='instruction',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='businessqueue',
            name='key',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='businessqueue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
