# Generated by Django 3.1 on 2022-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20220303_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='business',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='business',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='has_been_actived',
            new_name='has_been_activated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='to',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ready_time',
            new_name='will_be_ready_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='business.Item'),
        ),
    ]
