# Generated by Django 3.1 on 2022-03-04 18:03

import core.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20220304_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='units_available',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='to',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='_from',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_item', to='business.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_item', to='business.order')),
            ],
            options={
                'verbose_name': '[Business] Purchased Item ',
                'ordering': ['-created_at'],
            },
        ),
    ]
