# Generated by Django 3.1 on 2022-03-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20220308_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
