# Generated by Django 3.1 on 2022-02-18 10:11

import core.common.fields
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('minimum_age_allowed', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, db_index=False)),
                ('address', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('state', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('country', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('iso_code', models.CharField(max_length=2, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile')),
                ('timezone', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('ordering_feature_active', models.BooleanField(default=False)),
                ('has_orders', models.BooleanField(default=False)),
                ('total_amount_earned', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('total_amount_received', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '[Business Profile] ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_open', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('mo_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('mo_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '[Business Profile] Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_open', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('mo_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('mo_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('tu_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('we_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('th_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('fr_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('sa_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_o', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('su_c', core.common.fields.DefaultTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '[User Profile] Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('d_o_b', models.DateField()),
                ('ticket', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(max_length=255)),
                ('time', core.common.fields.DefaultTimeField(blank=True, null=True)),
                ('total_seconds', core.common.fields.DefaultIntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(max_length=255)),
                ('iso_code', models.CharField(max_length=2)),
                ('card_information', models.CharField(default='[]', max_length=1000000, null=True)),
            ],
            options={
                'verbose_name': '[User Profile]',
                'ordering': ['-created_at'],
            },
        ),
    ]
