# Generated by Django 3.1 on 2022-02-28 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220218_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='iso_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='key',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='minimum_age_allowed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='timezone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businessProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
