# Generated by Django 3.1 on 2022-03-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220228_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercalendar',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='UserCalendar',
        ),
    ]
