# Generated by Django 3.1 on 2022-03-08 12:23

import core.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220303_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='card_information',
        ),
        migrations.CreateModel(
            name='CardInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('card_bin', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('last4', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('exp_month', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('exp_year', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('brand', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('signature', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('account_name', core.common.fields.DefaultCharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='card', to='account.userprofile')),
            ],
            options={
                'verbose_name': '[User Profile] [Card Information]',
                'ordering': ['-created_at'],
            },
        ),
    ]
